export {default as Navbar} from './navbar/Navbar.jsx'
export {default as Header} from './header/Header.jsx'
export {default as Services} from './services/Services.jsx'
export {default as Description} from './desc/Description.jsx'
export {default as FAQS} from './FAQS/FAQS.jsx'
export {default as Blog} from './blog/Blog.jsx'
export {default as Footer} from './footer/Footer.jsx'
export {default as Article} from './article/Article.jsx'
